name: Deploy Next.js to Plesk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PLESK
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Instalar dependências
        run: npm install

      - name: Gerar build da aplicação
        run: npm run build

      - name: Preparar estrutura de arquivos
        run: |
          mkdir -p .next/standalone/public
          cp -r .next/static .next/standalone/
          cp -r public .next/standalone/

      - name: Deploy to Plesk
        uses: celleb/plesk-deployer@v1.1
        with:
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          ftp-server: ${{ secrets.FTP_SERVER }}
          files-to-copy: ".next/standalone/"
          remote-dir: "./brech.dev"
          node-version: 20
          npm-install: true
          restart: true
          clean-remote-dir: true
